'use strict';
(() => {
  const $ = id => document.getElementById(id);
  const W = window.DZWorld;
  if (!W) { $('loading-text').textContent = '3Dエンジンを読み込めません。WebGLとネット接続を確認し、再読み込みしてください。'; return; }
  const {T,scene,camera,renderer,tiers,mobile} = W;
  const FX=window.DZCombatFX(W);
  let Tactical=null;
  const weapons = [
    {id:0,name:'M9 SERVICE',jp:'信頼のサイドアーム',price:0,damage:28,rate:3.8,mag:12,reload:1.5,pellets:1,spread:.005,type:'9 × 19 MM · SEMI AUTO'},
    {id:1,name:'KRISS VECTOR',jp:'近距離を制圧するサブマシンガン',price:550,damage:29,rate:11,mag:30,reload:1.8,pellets:1,spread:.023,type:'.45 ACP · FULL AUTO'},
    {id:2,name:'M870 BREACHER',jp:'接近戦の切り札、散弾銃',price:950,damage:24,rate:1.05,mag:8,reload:2.5,pellets:8,spread:.071,type:'12 GAUGE · PUMP ACTION'},
    {id:3,name:'M4A1 CARBINE',jp:'威力と精度に優れたアサルトライフル',price:1500,damage:57,rate:7.5,mag:30,reload:2.1,pellets:1,spread:.011,type:'5.56 NATO · FULL AUTO'},
    {id:4,name:'M110 MARKSMAN',jp:'装甲を貫く精密射撃ライフル',price:2400,damage:240,rate:1.3,mag:10,reload:2.4,pellets:1,spread:.002,type:'7.62 NATO · PRECISION'},
    {id:5,name:'M249 REAPER',jp:'圧倒的火力を誇る軽機関銃',price:4200,damage:76,rate:10,mag:100,reload:3.6,pellets:1,spread:.023,type:'5.56 NATO · SUPPRESSIVE FIRE'}
  ];
  const upgrades = [
    {id:'health',name:'VITAL BOOST',jp:'最大体力',icon:'＋',desc:'最大体力 +25 / Lv。購入時に体力が全回復する。',base:180,max:5},
    {id:'damage',name:'LETHAL FORCE',jp:'武器ダメージ',icon:'⌖',desc:'全武器の威力 +15% / Lv。ヘッドショットにも適用。',base:250,max:5},
    {id:'armor',name:'IRON SKIN',jp:'防護装甲',icon:'⬡',desc:'受けるダメージ −8% / Lv。最大40%軽減。',base:220,max:5},
    {id:'speed',name:'GHOST STEP',jp:'移動速度',icon:'»',desc:'歩行とダッシュの移動速度 +8% / Lv。',base:180,max:4},
    {id:'reload',name:'QUICK HANDS',jp:'高速リロード',icon:'↻',desc:'リロード時間 −10% / Lv。最大40%短縮。',base:160,max:4},
    {id:'regen',name:'RECOVERY',jp:'自己再生',icon:'∿',desc:'5秒間被弾しないと、毎秒体力 +1 / Lv。',base:350,max:3}
  ];
  const selfTesting = new URLSearchParams(location.search).get('selftest') === '1';
  const captureMode = selfTesting && new URLSearchParams(location.search).get('capture') === '1';
  let capturedFrames=0;
  const emptySave = () => ({version:1,money:0,owned:[0],equipped:0,upgrades:{health:0,damage:0,armor:0,speed:0,reload:0,regen:0},bestWave:0,totalKills:0,inventory:{grenades:2,medkits:1}});
  const finiteInt=(n,min,max)=>Number.isFinite(Number(n))?Math.max(min,Math.min(max,Math.floor(Number(n)))):min;
  let saved=emptySave(),storageAvailable=true;
  try { const raw=JSON.parse(localStorage.getItem('deadzone-save-v1')); if(raw&&raw.version===1){saved.money=finiteInt(raw.money,0,99999999);saved.owned=[...new Set([0,...(Array.isArray(raw.owned)?raw.owned:[]).map(Number).filter(n=>Number.isInteger(n)&&n>=0&&n<6)])];saved.equipped=saved.owned.includes(Number(raw.equipped))?Number(raw.equipped):0;upgrades.forEach(u=>saved.upgrades[u.id]=finiteInt(raw.upgrades?.[u.id],0,u.max));saved.bestWave=finiteInt(raw.bestWave,0,99999);saved.totalKills=finiteInt(raw.totalKills,0,99999999);if(raw.inventory&&typeof raw.inventory==='object'){if(raw.inventory.grenades!==undefined)saved.inventory.grenades=finiteInt(raw.inventory.grenades,0,5);if(raw.inventory.medkits!==undefined)saved.inventory.medkits=finiteInt(raw.inventory.medkits,0,3);}} } catch(e){try{localStorage.getItem('deadzone-save-v1');}catch(error){storageAvailable=false;}}
  let persistTimer=0;function persistSoon(){if(persistTimer)return;persistTimer=setTimeout(()=>{persistTimer=0;persist();},800);}
  addEventListener('pagehide',()=>{if(persistTimer){clearTimeout(persistTimer);persistTimer=0;persist();}});
  function persist(){if(persistTimer){clearTimeout(persistTimer);persistTimer=0;}if(selfTesting)return;try{localStorage.setItem('deadzone-save-v1',JSON.stringify(saved));}catch(e){if(storageAvailable)toast('保存できません。ブラウザのストレージ設定をご確認ください。');storageAvailable=false;}}
  const state={mode:'menu',wave:0,kills:0,earned:0,hp:100,ammo:12,shotCooldown:0,reload:0,reloadTotal:0,spawnLeft:0,spawnTimer:0,nextWave:0,time:0,sinceHit:100,weapon:saved.equipped,aim:false,recoil:0,shooting:false,yaw:0,pitch:0,pointerLocked:false,shopTab:'weapons',lastModal:'',runTime:0};
  let zombies=[],menuZombies=[],effects=[],last=performance.now(),bannerTimer,toastTimer,flashTimer,hitTimer;
  const keys=new Set(),joy={x:0,y:0},look={active:false,x:0,y:0};
  const touchDefaults={sensitivity:1,adsSensitivity:.55,scale:1,opacity:.85,autoSprint:true,aimAssist:true,haptics:true};
  let touchPrefs={...touchDefaults},touchReset=()=>{};
  try{const p=JSON.parse(localStorage.getItem('deadzone-touch-v2')||'null');if(p){for(const k of ['sensitivity','adsSensitivity','scale','opacity'])if(Number.isFinite(p[k]))touchPrefs[k]=p[k];for(const k of ['autoSprint','aimAssist','haptics'])if(typeof p[k]==='boolean')touchPrefs[k]=p[k];}}catch(e){}
  touchPrefs.sensitivity=T.MathUtils.clamp(touchPrefs.sensitivity,.4,2);touchPrefs.adsSensitivity=T.MathUtils.clamp(touchPrefs.adsSensitivity,.25,1);touchPrefs.scale=T.MathUtils.clamp(touchPrefs.scale,.85,1.15);touchPrefs.opacity=T.MathUtils.clamp(touchPrefs.opacity,.35,1);
  function applyTouchPrefs(){document.documentElement.style.setProperty('--touch-scale',touchPrefs.scale);document.documentElement.style.setProperty('--touch-opacity',touchPrefs.opacity);}
  function haptic(ms){if(mobile&&touchPrefs.haptics&&navigator.vibrate)try{navigator.vibrate(ms);}catch(e){}}
  function syncTouchHUD(){for(const [id,on] of [['mobile-aim',state.aim],['mobile-sprint',state.touchSprint||state.autoSprinting]]){$(id).classList.toggle('active',!!on);$(id).setAttribute('aria-pressed',String(!!on));}$('mobile-fire').classList.toggle('is-firing',state.shooting);$('mobile-reload').classList.toggle('active',state.reload>0);document.body.classList.toggle('aiming',state.aim);}
  applyTouchPrefs();
  const maxHp=()=>100+saved.upgrades.health*25;
  const damageMultiplier=()=>1+saved.upgrades.damage*.15;
  const upgradeCost=u=>Math.round(u.base*Math.pow(1.65,saved.upgrades[u.id])/10)*10;
  let sound=false,audio=null,ambientNodes=[];
  function initAudio(){if(audio)return;try{audio=new (window.AudioContext||window.webkitAudioContext)();}catch(e){return;}const buffer=audio.createBuffer(1,audio.sampleRate*3,audio.sampleRate);const data=buffer.getChannelData(0);let value=0;for(let i=0;i<data.length;i++){value=(value+(Math.random()*2-1)*.018)/1.018;data[i]=value*3;}const noise=audio.createBufferSource();noise.buffer=buffer;noise.loop=true;const filter=audio.createBiquadFilter();filter.type='lowpass';filter.frequency.value=250;const gain=audio.createGain();gain.gain.value=0;noise.connect(filter);filter.connect(gain);gain.connect(audio.destination);noise.start();ambientNodes=[gain];}
  function setAudioActive(on){if(!audio)return;if(on&&sound)audio.resume?.().catch(()=>{});else if(!on)audio.suspend?.().catch(()=>{});}
  function updateSound(){ $('sound-toggle').innerHTML='♪ <span>SOUND '+(sound?'ON':'OFF')+'</span>';$('sound-toggle').setAttribute('aria-label',sound?'サウンドを無効にする':'サウンドを有効にする');$('sound-toggle').setAttribute('aria-pressed',String(sound));if(sound){initAudio();audio?.resume?.().catch(()=>{});}if(ambientNodes[0])ambientNodes[0].gain.setTargetAtTime(sound?.18:0,audio.currentTime,.2);}
  const noiseCache={};function noiseBuffer(key,duration,fill){if(!noiseCache[key]){const b=audio.createBuffer(1,Math.floor(audio.sampleRate*duration),audio.sampleRate);fill(b.getChannelData(0));noiseCache[key]=b;}return noiseCache[key];}
  function sfx(type){if(!sound||!audio)return;const now=audio.currentTime;const gain=audio.createGain();gain.connect(audio.destination);if(type==='explosion'||type==='thunder'){const duration=type==='thunder'?1.8:.8,b=noiseBuffer(type,duration,data=>{let previous=0;for(let i=0;i<data.length;i++){previous=previous*.85+(Math.random()*2-1)*.15;data[i]=previous*Math.pow(1-i/data.length,1.6);}});const src=audio.createBufferSource();src.buffer=b;gain.gain.value=type==='thunder'?.27:.5;src.connect(gain);src.start();src.onended=()=>{src.disconnect();gain.disconnect();};return;}if(type==='shoot'||type==='hit'){const duration=type==='shoot'?.15:.09;const b=noiseBuffer(type,duration,a=>{for(let i=0;i<a.length;i++)a[i]=(Math.random()*2-1)*Math.pow(1-i/a.length,2);});const src=audio.createBufferSource();src.buffer=b;const f=audio.createBiquadFilter();f.type='lowpass';f.frequency.value=type==='shoot'?(state.weapon===2?900:2200):450;src.connect(f);f.connect(gain);gain.gain.setValueAtTime(type==='shoot'?.45:.25,now);src.start();src.onended=()=>{src.disconnect();f.disconnect();gain.disconnect();};}else{const osc=audio.createOscillator();osc.type=type==='buy'?'sine':'triangle';osc.frequency.setValueAtTime(type==='buy'?520:type==='reload'?220:130,now);osc.frequency.exponentialRampToValueAtTime(type==='buy'?1000:70,now+.13);gain.gain.setValueAtTime(.12,now);gain.gain.exponentialRampToValueAtTime(.001,now+.18);osc.connect(gain);osc.start();osc.stop(now+.2);osc.onended=()=>{osc.disconnect();gain.disconnect();};}}
  $('sound-toggle').addEventListener('click',()=>{sound=!sound;updateSound();});
  $('quality-toggle').addEventListener('click',()=>{$('quality-label').textContent=W.setQuality();toast('ULTRA固定：フル解像度 / 4Kシャドウ / 高精細ディテール');});
  function toast(message){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').classList.add('visible');toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),2800);}
  function banner(title,subtitle,duration=3000){clearTimeout(bannerTimer);const b=$('wave-banner');b.textContent=title;const sm=document.createElement('small');sm.textContent=subtitle;b.appendChild(sm);$('wave-banner').style.opacity='1';bannerTimer=setTimeout(()=>$('wave-banner').style.opacity='0',duration);}
  const hudCache={};function setText(id,v){v=String(v);if(hudCache[id]!==v){hudCache[id]=v;$(id).textContent=v;}}
  function hud(){ Tactical?.updateHUD();setText('wave-value',String(state.wave).padStart(2,'0'));setText('enemies-value','感染体 '+(zombies.length+state.spawnLeft));setText('money-value',saved.money.toLocaleString());setText('health-value',Math.ceil(Math.max(0,state.hp)));setText('max-health-value','/ '+maxHp());$('health-bar').style.width=Math.max(0,state.hp/maxHp()*100)+'%';$('health-bar').style.background=state.hp<maxHp()*.3?'#e67551':'#b5c699';setText('armor-value','ARMOR '+saved.upgrades.armor*8+'%');setText('weapon-label',weapons[state.weapon].name);setText('ammo-value',state.ammo);$('ammo-value').classList.toggle('low',state.ammo<=Math.ceil(weapons[state.weapon].mag*.2));setText('reload-status',state.reload>0?'RELOADING '+state.reload.toFixed(1)+'s':weapons[state.weapon].type);}
  function disposeEnemy(z){W.disposeModel(z.root);}
  function makeMenuEnemies(){const positions=[[0,-2,0],[1,3,-12],[0,-3,-18],[2,5,-29],[3,1,-39],[0,-6,12],[1,7,-4]];positions.forEach(([tier,x,z])=>{const e=W.createZombie(tier,x,z);e.root.rotation.y=.18;menuZombies.push(e);});}
  makeMenuEnemies();
  function clearEffects(){effects.forEach(e=>{if(e.type==='body')disposeEnemy(e.enemy);else{scene.remove(e.mesh);if(!e.sharedGeometry)e.mesh.geometry?.dispose();e.mesh.material?.dispose();}});effects=[];}
  const lockSupported='requestPointerLock' in Element.prototype;
  function requestLock(){if(mobile||selfTesting||!lockSupported||document.pointerLockElement===renderer.domElement)return;try{const result=renderer.domElement.requestPointerLock();if(result?.catch)result.catch(()=>{toast('画面をクリックすると視点操作を開始します。');});}catch(e){state.lockFailed=true;toast('画面をドラッグして視点を操作できます。');}}
  document.addEventListener('pointerlockerror',()=>{if(!state.lockFailed&&state.mode==='playing')toast('マウスを固定できません。左ドラッグで視点を操作できます。');state.lockFailed=true;});
  function releaseLock(){if(document.pointerLockElement)document.exitPointerLock();state.pointerLocked=false;}
  function hideTransient(){$('scope-overlay').classList.add('hidden');document.body.classList.remove('scoped');W.muzzle&&(W.muzzle.visible=false);W.muzzleLight.intensity=0;state.blastShake=0;camera.rotation.z=0;$('hit-marker').style.opacity='0';}
  function clearInput(){keys.clear();state.shooting=false;state.aim=false;state.touchSprint=false;state.autoSprinting=false;joy.x=joy.y=0;$('move-knob').style.transform='';look.active=false;touchReset();syncTouchHUD();}
  function startGame(){for(const k in magazines)delete magazines[k];closeOverlay(false);clearInput();zombies.forEach(disposeEnemy);menuZombies.forEach(disposeEnemy);zombies=[];menuZombies=[];clearEffects();Tactical?.reset();state.mode='playing';state.wave=0;state.kills=0;state.earned=0;state.hp=maxHp();state.weapon=saved.equipped;state.ammo=weapons[state.weapon].mag;state.reload=0;state.shotCooldown=0;state.yaw=0;state.pitch=0;state.sinceHit=100;state.runTime=0;state.nextWave=0;state.recoil=0;state.blastShake=0;state.waveCleared=false;state.fromPause=false;hideTransient();camera.position.set(0,1.72,17);camera.rotation.set(0,0,0);camera.fov=68;camera.updateProjectionMatrix();W.buildGun(state.weapon);W.gun.visible=true;$('main-menu').classList.add('hidden');$('site-header').classList.add('hidden');$('game-hud').classList.remove('hidden');document.body.classList.add('playing');$('kill-feed').innerHTML='';if(sound){initAudio();audio?.resume?.().catch(()=>{});}requestLock();beginWave();hud();if(!storageAvailable)toast('この環境では保存が利用できません。進行は今回のプレイ中のみ保持されます。');}
  $('start-button').addEventListener('click',startGame);
  function beginWave(){state.waveCleared=false;state.wave++;Tactical?.beginWave(state.wave);state.spawnLeft=Math.min(6+Math.floor((state.wave-1)*2.5),35);state.spawnTimer=.1;state.nextWave=0;saved.bestWave=Math.max(saved.bestWave,state.wave);persist();banner('WAVE '+String(state.wave).padStart(2,'0'),state.wave===1?'感染体を排除し、報酬で武装せよ':state.wave===5?'暴君、接近。最大火力で迎え撃て。':'生き残れ。脅威は進化している。');hud();}
  function chooseTier(){if(state.wave>=5&&state.spawnLeft===1)return 4;if(state.wave>=4&&Math.random()<.15)return 3;if(state.wave>=3&&Math.random()<.23)return 2;if(state.wave>=2&&Math.random()<.36)return 1;return 0;}
  function addHealthBar(e){const g=new T.Group();e.root.add(g);g.position.y=2.35;const bg=new T.Sprite(new T.SpriteMaterial({color:0x162a25,depthTest:false}));bg.scale.set(.7,.055,1);g.add(bg);const fg=new T.Sprite(new T.SpriteMaterial({color:new T.Color(tiers[e.tier].hex),depthTest:false}));fg.scale.set(.7,.045,1);fg.center.set(0,.5);fg.position.set(-.35,0,.005);g.add(fg);e.healthBar=g;e.healthFill=fg;bg.userData.disposable=fg.userData.disposable=true;g.visible=false;}
  function spawnEnemy(){let x,z,best=null,bestScore=-Infinity;for(let tries=0;tries<25;tries++){const cx=W.rand(-7.5,7.5),direction=Math.random()<.78?-1:1,cz=T.MathUtils.clamp(camera.position.z+direction*W.rand(19,33),-80,33);if(W.blocked(cx,cz,.9))continue;const d=Math.hypot(cx-camera.position.x,cz-camera.position.z);if(d>=13){best=[cx,cz];break;}if(d>bestScore){bestScore=d;best=[cx,cz];}}if(!best)best=[0,camera.position.z>-50?-80:33];[x,z]=best;const e=W.createZombie(chooseTier(),x,z);if(state.wave>5){const scale=1+(state.wave-5)*.08;e.hp*=scale;e.maxHp=e.hp;e.damage*=1+(state.wave-5)*.045;}addHealthBar(e);zombies.push(e);state.spawnLeft--;hud();}
  function resumeGame(){closeOverlay(false);state.mode='playing';setAudioActive(true);last=performance.now();clearInput();requestLock();}
  function goMenu(){setAudioActive(true);state.mode='menu';releaseLock();closeOverlay(false);clearInput();hideTransient();zombies.forEach(disposeEnemy);zombies=[];clearEffects();Tactical?.reset();W.gun.visible=false;W.muzzleLight.intensity=0;camera.rotation.z=0;document.body.classList.remove('playing','aiming','scoped');state.aim=false;$('game-hud').classList.add('hidden');$('main-menu').classList.remove('hidden');$('site-header').classList.remove('hidden');camera.fov=62;camera.updateProjectionMatrix();if(!menuZombies.length)makeMenuEnemies();persist();}
  let returnMode='menu',previousFocus=null;
  function openModal(type){if(state.mode==='dead'&&type!=='death')return;if(state.mode==='playing'){returnMode='playing';state.mode='paused';clearInput();releaseLock();hideTransient();if(type!=='shop')setAudioActive(false);}else if(state.mode==='menu')returnMode='menu';if($('overlay').classList.contains('hidden'))previousFocus=document.activeElement;$('overlay').setAttribute('aria-hidden','false');state.lastModal=type;if(type==='shop')setAudioActive(true);$('overlay').classList.remove('hidden');$('modal').style.maxWidth=type==='pause'||type==='death'?'550px':'';renderModal(type);$('modal-close').focus();}
  function closeOverlay(resume=true){$('overlay').classList.add('hidden');$('overlay').setAttribute('aria-hidden','true');if(resume&&returnMode==='playing'&&state.mode==='paused'){state.mode='playing';setAudioActive(true);last=performance.now();requestLock();}state.lastModal='';if(previousFocus?.isConnected&&previousFocus.offsetParent!==null&&state.mode!=='playing')previousFocus.focus();else if(document.activeElement&&$('modal').contains(document.activeElement))document.activeElement.blur();}
  function backOrClose(){if(state.mode==='dead')goMenu();else if(state.mode==='paused'&&state.fromPause&&state.lastModal!=='pause'){state.fromPause=false;openModal('pause');}else{state.fromPause=false;closeOverlay();}}
  $('modal-close').addEventListener('click',backOrClose);
  $('overlay').addEventListener('click',e=>{if(e.target===$('overlay')&&state.mode!=='dead')backOrClose();});
  function gunSvg(index){if(index===0)return '<svg viewBox="0 0 210 75" aria-hidden="true"><path fill="currentColor" d="M36 20h129v19h-66l-3 7 8 24H73L60 41H36z"/><path fill="#4b5f50" d="M40 24h115v4H40zm24 19h25l5 24H79z"/><path fill="none" stroke="currentColor" stroke-width="4" d="M101 39v14h-8"/><path fill="#171f1d" d="M144 20v18h4V20z"/></svg>';return '<svg viewBox="0 0 230 75" aria-hidden="true"><path fill="currentColor" d="M8 25l34 2 8-8h76l12 6h55v5h27v5h-32v9h-64l-14 8 4 19H95l-7-25H68L47 37l-7 20H8z"/><path fill="#364a3c" d="M130 28h51v9h-51zM93 49h12l5 18H99zM13 32h24v15H13z"/><path fill="currentColor" d="M67 43h19l-4 24H67zM58 15h68v5H58z"/>'+(index===4?'<path fill="currentColor" d="M85 9h54v9H85zM99 17v5h8v-5z"/>':'')+(index===5?'<path fill="currentColor" d="M117 43h25v25h-25z"/>':'')+'<path stroke="#1d2c22" stroke-width="2" d="M142 27v12m7-12v12m7-12v12m7-12v12m7-12v12"/></svg>';}
  function renderModal(type){const titles={shop:'補給・武器庫',bestiary:'感染体データベース',guide:'生存者フィールドマニュアル',pause:'戦線、一時停止',death:'戦線離脱',settings:'タッチ操作設定'};$('modal-title').textContent=titles[type]||'';$('modal-eyebrow').textContent=type==='shop'?'FIELD ARMORY / PREPARE FOR THE NEXT WAVE':type==='death'?'SIGNAL LOST / SURVIVOR DOWN':type==='bestiary'?'THREAT INTELLIGENCE / CLASSIFIED':'DEADZONE / FIELD MANUAL';
    if(type==='settings'){renderTouchSettings();return;}
    if(type==='shop'){renderShop();return;}
    if(type==='bestiary'){$('modal-content').innerHTML='<div class="shop-summary"><p>感染には5つの段階がある。特性を知ることが、生存への第一歩。<br>表示は基本値。ウェーブ6以降は体力・攻撃力がさらに増加する。</p></div><div class="bestiary-list">'+tiers.map((t,i)=>'<article class="enemy-card" style="--tier:'+t.hex+'"><span class="enemy-tier">0'+(i+1)+'</span><div><h3>'+t.name+'<small>'+t.en+'</small></h3><p>'+t.desc+'</p></div><div class="enemy-stats"><span>HEALTH<b>'+t.hp+'</b></span><span>DAMAGE<b>'+t.damage+'</b></span><span class="reward">REWARD<b>₡ '+t.reward+'</b></span></div></article>').join('')+'</div><p class="dialog-note">頭部命中で2.2倍ダメージ。装甲兵の胴体は被ダメージを35%軽減。報酬は倒した瞬間に入金されます。</p>';return;}
    if(type==='guide'){$('modal-content').innerHTML='<div class="guide-grid">'+(mobile?[['移動 / 自動ダッシュ','左スティック'],['視点操作','右スワイプ'],['射撃＋照準移動','FIRE 長押し＋スライド'],['精密照準 切替','⌖ ボタン'],['リロード / 無限予備弾','↻ ボタン'],['ダッシュ 切替','» ボタン'],['武器切替 / 購入','⇄ / 補給・武器庫'],['手榴弾 / 治療','◉ / ✚'],['感度・振動 / 停止','⚙ / Ⅱ']]:[['移動','W A S D / 矢印'],['視点操作','マウス'],['射撃（長押し可）','左クリック'],['精密照準','右クリック'],['リロード / 無限予備弾','R'],['ダッシュ','SHIFT'],['武器庫 / 強化','B'],['武器切替','1〜6 / Q / ホイール'],['手榴弾 / 治療','G / H'],['一時停止','ESC / P']]).map(([label,key])=>'<div class="guide-row"><span>'+label+'</span><kbd>'+key+'</kbd></div>').join('')+'</div><div class="info-block"><strong>01 — 排除して稼ぐ。</strong> 全感染体を倒すとウェーブクリア。5秒後に次の襲撃が始まります。クリア時は体力が25回復し、ボーナスも支給。<br><strong>02 — 装備を進化させる。</strong> いつでも B キーで武器庫へ。購入中は時間が停止します。武器を装備すると弾倉が補充されます。<br><strong>03 — 補給を活かす。</strong> 手榴弾（G／◉）は1.8秒で爆発。回復（H／✚）には2秒必要で、被弾で中断。消耗品は武器庫の「補給」タブから購入できます。<br><strong>04 — 追加報酬を狙う。</strong> 毎ウェーブの作戦目標を達成するとボーナス。5秒以内の連続撃破にも追加報酬が付きます。<br><strong>05 — 頭部を狙う。</strong> ヘッドショットは威力2.2倍。右クリックで照準を絞り、強敵には距離を取って対処しましょう。</div><p class="dialog-note"><strong>スマートフォン：</strong>左スティックで移動、画面右側のスワイプで視点操作。FIREを長押し＋スライドで射撃しながら照準操作。⌖で精密照準、»でダッシュ、↻でリロード、⇄で武器切替。⚙から感度・サイズ・振動を調整できます。PCはゲーム画面をクリックするとマウスが固定されます。固定できない環境では左ドラッグで視点移動できます。<br><strong>セーブ：</strong>所持金・武器・強化・最高ウェーブはこのブラウザに保存されます。プレイ中の位置や現在のウェーブは再開できません。戦線離脱しても購入状況と所持金は失いません。<br>本作には架空の感染体への銃撃表現があります。</p>';return;}
    if(type==='pause'){$('modal-content').innerHTML='<div class="pause-body"><p>作戦区域の時間は停止しています。<br>次の一歩を、慎重に。</p><button class="primary-button" data-modal-action="resume">▷ 戦線に戻る</button><button class="secondary-button" data-modal-action="shop">補給・武器庫</button><button class="secondary-button" data-modal-action="guide">操作ガイド</button><br><button class="secondary-button" data-modal-action="sound">♪ サウンド切替</button><button class="secondary-button" data-modal-action="settings">⚙ タッチ操作設定</button><button class="secondary-button weather-status" data-modal-action="weather">☂ 雨・雷の切替</button><br><button class="secondary-button" data-modal-action="menu">タイトルへ戻る</button><p class="dialog-note">所持金・購入済み装備は保存されます。<br>タイトルへ戻ると現在のウェーブは終了します。</p></div>';return;}
    if(type==='death'){$('modal-content').innerHTML='<div class="pause-body"><p>信号が途絶えた。だが、戦いは終わらない。<br>装備と所持金は、次の生存者へ引き継がれる。</p><div class="death-stats"><div><small>到達ウェーブ</small><b>'+state.wave+'</b></div><div><small>撃破数</small><b>'+state.kills.toLocaleString()+'</b></div><div><small>獲得報酬</small><b>'+state.earned.toLocaleString()+'</b></div></div><div class="operation-result"><span>作戦達成 <b>'+(Tactical?.summary.contractsCompleted||0)+'</b></span><span>追加報酬 <b>₡ '+(Tactical?.summary.earnedBonus||0).toLocaleString()+'</b></span></div><button class="primary-button" data-modal-action="restart">↻ もう一度、戦線へ</button><button class="secondary-button" data-modal-action="menu">タイトルへ戻る</button><p class="dialog-note">最高到達 WAVE '+saved.bestWave+' / 累計撃破 '+saved.totalKills.toLocaleString()+'</p></div>';}
  }
  function saveTouchPrefs(){if(selfTesting)return;try{localStorage.setItem('deadzone-touch-v2',JSON.stringify(touchPrefs));}catch(e){toast('操作設定を保存できませんでした');}}
  function renderTouchSettings(){const sliders=[['sensitivity','視点の感度',.4,2,.05],['adsSensitivity','照準中の感度',.25,1,.05],['scale','操作ボタンのサイズ',.85,1.15,.05],['opacity','操作ボタンの濃さ',.35,1,.05]];const toggles=[['autoSprint','スティックで自動ダッシュ','上へ大きく倒すとダッシュ。通常は倒した量に応じて移動。'],['aimAssist','微調整エイムアシスト','照準付近の敵を穏やかに追従。自動射撃はしません。'],['haptics','触覚フィードバック','射撃・被弾時に振動。対応端末のみ有効。']];$('modal-content').innerHTML='<div class="touch-settings"><div class="quality-spec"><b>ULTRA</b><p>フル解像度・アンチエイリアス<br>4Kシャドウ / 小物密度 ×5<br>自動的な画質低下なし</p></div>'+sliders.map(([id,label,min,max,step])=>'<section class="setting-card"><label for="pref-'+id+'">'+label+'<output id="out-'+id+'">'+Math.round(touchPrefs[id]*100)+'%</output></label><input id="pref-'+id+'" data-pref="'+id+'" type="range" min="'+min+'" max="'+max+'" step="'+step+'" value="'+touchPrefs[id]+'"></section>').join('')+toggles.map(([id,label,desc])=>'<section class="setting-card"><label for="pref-'+id+'">'+label+'<input id="pref-'+id+'" data-pref="'+id+'" type="checkbox" '+(touchPrefs[id]?'checked':'')+'></label><p>'+desc+'</p></section>').join('')+'<p class="touch-layout-note">左親指で移動、右親指で照準。射撃ボタンを押したままスライドすると、射撃と視点移動を同時に操作できます。照準・ダッシュはタップで切り替え。縦持ち・横持ちの両方に対応しています。</p><div class="setting-actions"><button data-modal-action="fullscreen">⛶ 全画面・横画面</button><button data-modal-action="reset-touch">操作設定を初期化</button></div><p class="dialog-note">全画面表示・向きの固定は、対応するブラウザでのみ利用できます。非対応の場合は端末を横向きにしてお楽しみください。</p></div>';}
  $('modal-content').addEventListener('input',e=>{const el=e.target,id=el.dataset.pref;if(!(id in touchDefaults))return;touchPrefs[id]=el.type==='checkbox'?el.checked:Math.round(Number(el.value)*100)/100;if($('out-'+id))$('out-'+id).textContent=Math.round(touchPrefs[id]*100)+'%';applyTouchPrefs();saveTouchPrefs();});
  async function enterFullscreen(){try{if(!document.documentElement.requestFullscreen){toast('このブラウザでは全画面切替は非対応です。端末を横向きにしてください。');return;}await document.documentElement.requestFullscreen();try{if(screen.orientation?.lock)await screen.orientation.lock('landscape');}catch(e){toast('全画面表示になりました。横画面は端末を回転してください。');}}catch(e){toast('全画面表示が許可されていません。端末を横向きにしてプレイできます。');}}
  function applyAimAssist(dt){if(!mobile||!touchPrefs.aimAssist||(!state.aim&&!state.shooting))return;let best=null,angle=.06;for(const e of zombies){const dx=e.root.position.x-camera.position.x,dz=e.root.position.z-camera.position.z,distance=Math.hypot(dx,dz);if(distance<1||distance>28)continue;const yaw=Math.atan2(-dx,-dz),pitch=Math.atan2(1.4*e.scale-camera.position.y,distance),dyaw=Math.atan2(Math.sin(yaw-state.yaw),Math.cos(yaw-state.yaw)),dpitch=pitch-state.pitch,a=Math.hypot(dyaw,dpitch);if(a<angle){const eye=camera.position,dir=new T.Vector3(dx,1.4*e.scale-eye.y,dz),len=dir.length();dir.divideScalar(len);if(W.rayObstacle(eye,dir,len))continue;angle=a;best={dyaw,dpitch};}}if(best){state.yaw+=best.dyaw*Math.min(1,dt*.9);state.pitch+=best.dpitch*Math.min(1,dt*.65);}}
  function renderShop(){let html='<div class="shop-summary"><p>生き延びるための投資を。購入・装備は即時反映。<br>武器庫を開いている間、戦闘は停止します。</p><span class="shop-balance">₡ '+saved.money.toLocaleString()+'</span></div><div class="shop-tabs"><button data-tab="weapons" class="'+(state.shopTab==='weapons'?'active':'')+'">武器 / WEAPONS</button><button data-tab="upgrades" class="'+(state.shopTab==='upgrades'?'active':'')+'">能力強化 / UPGRADES</button><button data-tab="supplies" class="tab-supplies '+(state.shopTab==='supplies'?'active':'')+'">補給 / SUPPLY</button></div><div class="shop-grid">';
    if(state.shopTab==='weapons')html+=weapons.map(w=>{const owned=saved.owned.includes(w.id),equipped=saved.equipped===w.id;return '<article class="item-card '+(equipped?'equipped':'')+'"><span class="item-tier">CLASS 0'+(w.id+1)+' / '+(owned?'OWNED':'AVAILABLE')+'</span><div class="weapon-art">'+gunSvg(w.id)+'</div><h3>'+w.name+'</h3><span class="item-jp">'+w.jp+'</span><div class="item-stats"><span>DMG <b>'+Math.round(w.damage*damageMultiplier())+(w.pellets>1?' ×'+w.pellets:'')+'</b></span><span>MAG <b>'+w.mag+'</b></span><span>RPM <b>'+Math.round(w.rate*60)+'</b></span></div><button data-buy-weapon="'+w.id+'" '+(equipped||(!owned&&saved.money<w.price)?'disabled':'')+'>'+(equipped?'✓ 装備中':owned?'装備する':'₡ '+w.price.toLocaleString()+' — 購入')+'</button></article>';}).join('');
    else if(state.shopTab==='upgrades')html+=upgrades.map(u=>{const lv=saved.upgrades[u.id],cost=upgradeCost(u);return '<article class="item-card"><span class="upgrade-icon">'+u.icon+'</span><h3>'+u.name+'</h3><span class="item-jp">'+u.jp+'</span><p class="upgrade-description">'+u.desc+'</p><div class="upgrade-level">'+'■ '.repeat(lv)+'□ '.repeat(u.max-lv)+'<span> LV '+lv+' / '+u.max+'</span></div><button data-upgrade="'+u.id+'" '+(lv>=u.max||saved.money<cost?'disabled':'')+'>'+(lv>=u.max?'最大強化済み':'₡ '+cost.toLocaleString()+' — 強化')+'</button></article>';}).join('');
    else html+=Tactical.supplyCards();
    html+='</div><p class="dialog-note">'+(state.shopTab==='weapons'?'予備弾薬は無制限。弾倉が空になると自動でリロード。購入済みの武器は何度でも無料で切り替えられます。':state.shopTab==='supplies'?'補給品は消耗品です。残数はセーブされ、再出撃しても自動補充されません。':'全強化は永続効果。死亡・再出撃後も引き継がれます。')+'<br>最高到達 WAVE '+saved.bestWave+' · 累計撃破 '+saved.totalKills+' · 保存先：この端末のブラウザ</p>';$('modal-content').innerHTML=html;
  }
  const magazines={};function buyWeapon(id){const w=weapons[id];if(!w)return false;const bought=!saved.owned.includes(id);if(bought){if(saved.money<w.price)return false;saved.money-=w.price;saved.owned.push(id);}if(state.weapon!==id)magazines[state.weapon]=state.ammo;saved.equipped=id;state.weapon=id;state.ammo=bought||state.mode!=='playing'||magazines[id]===undefined?w.mag:magazines[id];state.reload=0;state.shotCooldown=0;W.buildGun(id);persist();hud();sfx('buy');toast(w.name+' を装備しました');if(state.mode==='playing'&&state.ammo===0)reload();return true;}
  function switchWeapon(id){if(state.mode!=='playing'||id===state.weapon)return false;if(!saved.owned.includes(id)){toast(weapons[id]?weapons[id].name+' は未購入です（武器庫で購入）':'');return false;}return buyWeapon(id);}
  function cycleWeapon(step){const owned=[...saved.owned].sort((a,b)=>a-b);if(owned.length<2){toast('武器庫で別の武器を購入すると切り替えられます');return false;}const i=owned.indexOf(state.weapon);return switchWeapon(owned[(i+step+owned.length)%owned.length]);}
  function buyUpgrade(id){const u=upgrades.find(x=>x.id===id);if(!u||saved.upgrades[id]>=u.max)return false;const cost=upgradeCost(u);if(saved.money<cost)return false;saved.money-=cost;const before=1-saved.upgrades.reload*.1;saved.upgrades[id]++;if(id==='health')state.hp=maxHp();if(id==='reload'&&state.reload>0){const ratio=(1-saved.upgrades.reload*.1)/before;state.reload*=ratio;state.reloadTotal*=ratio;}persist();hud();sfx('buy');toast(u.jp+' を強化しました');return true;}
  $('modal-content').addEventListener('click',e=>{const el=e.target.closest('button');if(!el)return;if(el.dataset.tab){state.shopTab=el.dataset.tab;renderShop();}else if(el.dataset.buyWeapon!==undefined){buyWeapon(Number(el.dataset.buyWeapon));renderShop();}else if(el.dataset.supply){Tactical.buySupply(el.dataset.supply);renderShop();}else if(el.dataset.upgrade){buyUpgrade(el.dataset.upgrade);renderShop();}else{switch(el.dataset.modalAction){case 'resume':resumeGame();break;case 'restart':startGame();break;case 'menu':goMenu();break;case 'shop':state.fromPause=state.lastModal==='pause';openModal('shop');break;case 'guide':state.fromPause=state.lastModal==='pause';openModal('guide');break;case 'sound':sound=!sound;updateSound();toast('サウンド '+(sound?'ON':'OFF'));break;case 'quality':$('quality-toggle').click();break;case 'weather':toast(FX.toggleWeather()?'雨・雷 ON':'雨・雷 OFF');break;case 'settings':state.fromPause=state.lastModal==='pause';openModal('settings');break;case 'fullscreen':enterFullscreen();break;case 'reset-touch':touchPrefs={...touchDefaults};applyTouchPrefs();saveTouchPrefs();renderTouchSettings();break;}}});
  document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>{const action=b.dataset.action;if(action==='home'){if(state.mode==='menu')toast('隔離区域への準備完了。戦線に降り立とう。');else goMenu();}else openModal(action);}));
  $('touch-settings-button').addEventListener('click',()=>openModal('settings'));
  $('mobile-shop').addEventListener('click',()=>openModal('shop'));
  $('game-hud').addEventListener('mousedown',e=>{if(e.target.closest('button'))e.preventDefault();});
  $('shop-button').addEventListener('click',()=>openModal('shop'));$('pause-button').addEventListener('click',()=>openModal('pause'));
  function reload(){if(state.mode!=='playing'||state.reload>0||state.ammo>=weapons[state.weapon].mag||Tactical?.healing)return;state.reloadTotal=weapons[state.weapon].reload*(1-saved.upgrades.reload*.1);state.reload=state.reloadTotal;sfx('reload');hud();}
  const ray=new T.Ray(),direction=new T.Vector3(),hitPoint=new T.Vector3(),sphere=new T.Sphere(),forward=new T.Vector3();
  function intersectEnemy(origin,dir,maxDistance=90,matricesFresh=false){ray.set(origin,dir);let found=null,nearest=maxDistance;if(!matricesFresh)zombies.forEach(z=>z.root.updateMatrixWorld(true));for(const z of zombies){const scale=z.scale;const zones=[{joint:z.head,r:.22,head:true},{joint:z.torso,r:.35,head:false},{joint:z.rig.pelvis,r:.29,head:false},{joint:z.rig.knees[0],r:.15,limb:true},{joint:z.rig.knees[1],r:.15,limb:true},{joint:z.rig.feet[0],r:.13,limb:true},{joint:z.rig.feet[1],r:.13,limb:true},{joint:z.rig.elbows[0],r:.12,limb:true},{joint:z.rig.elbows[1],r:.12,limb:true}];for(const zone of zones){zone.joint.getWorldPosition(sphere.center);if(zone.joint===z.torso)sphere.center.y+=.12*scale;sphere.radius=zone.r*scale;const h=ray.intersectSphere(sphere,hitPoint);if(h){const distance=origin.distanceTo(h);if(distance<nearest){nearest=distance;found={enemy:z,head:!!zone.head,limb:!!zone.limb,point:h.clone(),distance};}}}}
    // Bullets do not pass through the solid bodies of cars and barriers.
    if(found&&W.rayObstacle(origin,dir,nearest))return null;
    return found;
  }
  function sideOf(e,point){const ry=e.root.rotation.y,dx=point.x-e.root.position.x,dz=point.z-e.root.position.z;return dx*Math.cos(ry)-dz*Math.sin(ry)>=0?1:-1;}
  const particleGeo=new T.BoxGeometry(.035,.035,.035);
  function particle(point,color,count=7){for(let i=0;i<count;i++){const m=new T.Mesh(particleGeo,new T.MeshBasicMaterial({color}));m.position.copy(point);scene.add(m);effects.push({mesh:m,sharedGeometry:true,life:.35,max:.35,velocity:new T.Vector3((Math.random()-.5)*3,Math.random()*2,(Math.random()-.5)*3),type:'particle'});}}
  function tracer(target){const origin=new T.Vector3();if(W.muzzle){W.muzzle.updateWorldMatrix(true,false);W.muzzle.getWorldPosition(origin);}else origin.set(.3,-.23,-1).applyMatrix4(camera.matrixWorld);const geo=new T.BufferGeometry().setFromPoints([origin,target]);const line=new T.Line(geo,new T.LineBasicMaterial({color:0xf5cc80,transparent:true,opacity:.45}));scene.add(line);effects.push({mesh:line,life:.045,max:.045,type:'tracer'});}
  function fire(){if(state.mode!=='playing'||state.shotCooldown>0||state.reload>0||Tactical?.healing)return;if(state.ammo<=0){reload();return;}const w=weapons[state.weapon];state.ammo--;state.shotCooldown=Math.min(0,state.shotCooldown)+1/w.rate;zombies.forEach(z=>z.root.updateMatrixWorld(true));state.recoil=Math.min(.16,state.recoil+(w.id===2?.1:.055));W.muzzle.visible=true;W.muzzle.material.rotation=Math.random()*6;W.muzzleLight.intensity=8;state.flashUntil=state.time+.05;sfx('shoot');haptic(8);camera.updateMatrixWorld();camera.getWorldDirection(forward);FX.shell(state.weapon);let hitAny=false,headAny=false,lastPoint=null;
    for(let i=0;i<w.pellets;i++){direction.copy(forward);const spread=w.spread*(state.aim?.45:1);direction.x+=(Math.random()-.5)*spread;direction.y+=(Math.random()-.5)*spread;direction.z+=(Math.random()-.5)*spread;direction.normalize();const surface=FX.surfaceHit(camera.position,direction);const hit=intersectEnemy(camera.position,direction,surface?surface.distance:90,true);if(hit){hitAny=true;headAny=headAny||hit.head;const e=hit.enemy;let damage=w.damage*damageMultiplier()*(hit.head?2.2:1);if(hit.limb)damage*=.8;else if(e.tier===2&&!hit.head)damage*=.65;if(w.id===2)damage*=T.MathUtils.clamp(1-(hit.distance-7)*.024,.35,1);e.hp-=damage;W.reactToHit(e,hit.head,sideOf(e,hit.point));e.healthBar.visible=true;e.healthFill.scale.x=.7*Math.max(0,e.hp/e.maxHp);particle(hit.point,hit.head?0xc4b981:0x785c3f,w.pellets>1?2:5);lastPoint=hit.point;if(e.hp<=0)kill(e,hit.head);}else{lastPoint=surface?surface.point:camera.position.clone().addScaledVector(direction,60);if(surface)FX.impact(surface);}}
    if(lastPoint)tracer(lastPoint);if(hitAny){clearTimeout(hitTimer);$('hit-marker').style.color=headAny?'#f59c59':'#f4edd5';$('hit-marker').style.opacity='1';hitTimer=setTimeout(()=>$('hit-marker').style.opacity='0',120);}hud();if(state.ammo===0)setTimeout(()=>{if(state.mode==='playing'&&state.ammo===0)reload();},200);
  }
  function kill(e,head,source='gun'){const idx=zombies.indexOf(e);if(idx<0)return;zombies.splice(idx,1);const t=tiers[e.tier];saved.money+=t.reward;state.earned+=t.reward;state.kills++;saved.totalKills++;if(state.mode==='playing')Tactical?.onKill(head,source);if(e.healthBar)e.healthBar.visible=false;W.startDeath(e,head);effects.push({mesh:e.root,life:7.5,max:7.5,type:'body',enemy:e});const feed=document.createElement('div');feed.className='feed-item';feed.textContent=(head?'HEADSHOT / ':'')+t.name;const reward=document.createElement('span');reward.textContent='+ ₡ '+t.reward;feed.appendChild(reward);$('kill-feed').prepend(feed);while($('kill-feed').children.length>4)$('kill-feed').lastChild.remove();setTimeout(()=>feed.remove(),3200);persistSoon();hud();}
  function takeDamage(amount){Tactical?.cancelHeal();state.hp-=Math.max(0,amount)*Math.max(.6,1-saved.upgrades.armor*.08);state.sinceHit=0;sfx('hit');haptic([20,25,35]);clearTimeout(flashTimer);$('damage-flash').style.opacity='.6';flashTimer=setTimeout(()=>$('damage-flash').style.opacity='0',160);hud();if(state.hp<=0){state.hp=0;state.mode='dead';clearInput();releaseLock();hideTransient();W.gun.visible=false;persist();returnMode='menu';openModal('death');}}
  function canMove(x,z,r=.35){if(x<-8.9+r||x>8.9-r||z<-84+r||z>35-r)return false;return !W.blocked(x,z,r);}
  function movePlayer(dt){let dx=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+joy.x;let dz=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0)+joy.y;const len=Math.hypot(dx,dz);if(len>1){dx/=len;dz/=len;}const speed=4.2*(1+saved.upgrades.speed*.08)*(keys.has('ShiftLeft')||keys.has('ShiftRight')||state.touchSprint||state.autoSprinting?1.5:1)*(state.aim?.65:1);const c=Math.cos(state.yaw),s=Math.sin(state.yaw);const mx=(dx*c+dz*s)*speed*dt,mz=(-dx*s+dz*c)*speed*dt;if(canMove(camera.position.x+mx,camera.position.z))camera.position.x+=mx;if(canMove(camera.position.x,camera.position.z+mz))camera.position.z+=mz;for(const e of zombies){const ox=camera.position.x-e.root.position.x,oz=camera.position.z-e.root.position.z,d=Math.hypot(ox,oz),min=.32*e.scale+.35;if(d<min&&d>.0001){const push=min-d,nx=camera.position.x+ox/d*push,nz=camera.position.z+oz/d*push;if(canMove(nx,camera.position.z))camera.position.x=nx;if(canMove(camera.position.x,nz))camera.position.z=nz;}}camera.position.y=1.72+(len>.1?Math.sin(state.runTime*11)*.035:0);state.moving=len>.1;}
  const meleeFrom=new T.Vector3(),meleeDir=new T.Vector3();function meleeBlocked(p){meleeFrom.set(p.x,.7,p.z);meleeDir.set(camera.position.x-p.x,0,camera.position.z-p.z);const len=meleeDir.length();if(len<.05)return false;meleeDir.divideScalar(len);return !!W.rayObstacle(meleeFrom,meleeDir,len);}
  function updateEnemies(dt){for(const e of zombies){const p=e.root.position;let dx=camera.position.x-p.x,dz=camera.position.z-p.z;const distance=Math.hypot(dx,dz),targetYaw=Math.atan2(dx,dz);const turn=Math.atan2(Math.sin(targetYaw-e.root.rotation.y),Math.cos(targetYaw-e.root.rotation.y));e.root.rotation.y=Math.atan2(Math.sin(e.root.rotation.y),Math.cos(e.root.rotation.y))+T.MathUtils.clamp(turn,-dt*(e.tier>=3?2.3:4.2),dt*(e.tier>=3?2.3:4.2));e.attack=Math.max(0,e.attack-dt);const stopDistance=.78*e.scale+.3;const attacking=e.anim.attackTime>=0;const oldX=p.x,oldZ=p.z;if(distance>stopDistance&&!attacking){dx/=distance;dz/=distance;
        for(const o of W.obstacles){if(o.shape==='cyl'&&Math.hypot(p.x-o.x,p.z-o.z)>2)continue;const ox=p.x-o.x,oz=p.z-o.z,dist=Math.hypot(ox,oz);if(dist<o.r+1.4){const strength=(o.r+1.4-dist)/1.4;dx+=ox/(dist||1)*strength*1.8;dz+=oz/(dist||1)*strength*1.8;const cross=ox*dz-oz*dx;dx+=(-oz/(dist||1))*.6*(cross>=0?1:-1);dz+=(ox/(dist||1))*.6*(cross>=0?1:-1);}}
        for(const other of zombies){if(other===e)continue;const ox=p.x-other.root.position.x,oz=p.z-other.root.position.z,dist=Math.hypot(ox,oz),space=.5*(e.scale+other.scale);if(dist<space&&dist>.001){dx+=ox/dist*(space-dist);dz+=oz/dist*(space-dist);}}
        const norm=Math.hypot(dx,dz)||1,limp=e.hp<e.maxHp*.35?.8:1,stagger=1-e.anim.hit*(e.tier<3?.55:.15),step=e.speed*dt*limp*stagger;const nx=p.x+dx/norm*step,nz=p.z+dz/norm*step;const mvx=canMove(nx,p.z,.25),mvz=canMove(p.x,nz,.25);if(mvx)p.x=nx;if(mvz)p.z=nz;if(!mvx&&!mvz){const side=(e.phase>Math.PI?1:-1),tx=p.x+(-dz/norm)*step*side,tz=p.z+(dx/norm)*step*side;if(canMove(tx,tz,.25)){p.x=tx;p.z=tz;}}
      }else if(distance<=stopDistance+.2&&e.attack<=0&&!attacking){e.attack=e.tier>=3?1.7:1.35;W.triggerAttack(e);}
      const motion=W.animateZombie(e,state.time,Math.hypot(p.x-oldX,p.z-oldZ)>.00001,dt);
      if(motion.impact&&Math.hypot(camera.position.x-p.x,camera.position.z-p.z)<stopDistance+.6&&Math.abs(turn)<1.1&&!meleeBlocked(p)){takeDamage(e.damage);if(state.mode!=='playing')break;}
      if(e.healthBar)e.healthBar.visible=e.hp<e.maxHp&&distance<30;
    }}
  function updateEffects(dt){for(let i=effects.length-1;i>=0;i--){const e=effects[i];e.life-=dt;if(e.type==='body'){W.animateDeath(e.enemy,dt);}else if(e.velocity){e.velocity.y-=8*dt;e.mesh.position.addScaledVector(e.velocity,dt);e.mesh.rotation.x+=dt*5;}if(e.life<=0){if(e.type==='body')disposeEnemy(e.enemy);else{scene.remove(e.mesh);if(!e.sharedGeometry)e.mesh.geometry.dispose();e.mesh.material.dispose();}effects.splice(i,1);}}}
  const radarContext=$('radar').getContext('2d');
  function drawRadar(){const c=radarContext;c.clearRect(0,0,220,220);c.save();c.translate(110,110);c.strokeStyle='#a2b99324';c.lineWidth=1;for(const r of [50,100]){c.beginPath();c.arc(0,0,r,0,Math.PI*2);c.stroke();}c.beginPath();c.moveTo(-105,0);c.lineTo(105,0);c.moveTo(0,-105);c.lineTo(0,105);c.stroke();c.fillStyle='#b1ca9720';c.beginPath();c.moveTo(0,0);c.arc(0,0,100,-Math.PI*.68,-Math.PI*.32);c.closePath();c.fill();const cos=Math.cos(state.yaw),sin=Math.sin(state.yaw);for(const e of zombies){const dx=e.root.position.x-camera.position.x,dz=e.root.position.z-camera.position.z;const dist=Math.hypot(dx,dz);if(dist>60)continue;const k=dist>40?40/dist:1;const x=(dx*cos-dz*sin)*2.5*k,y=(dx*sin+dz*cos)*2.5*k;c.globalAlpha=dist>40?.45:1;c.fillStyle=tiers[e.tier].hex;c.beginPath();c.arc(x,y,3+e.tier*.5,0,Math.PI*2);c.fill();}c.globalAlpha=1;c.fillStyle='#e8e9cc';c.beginPath();c.moveTo(0,-7);c.lineTo(5,5);c.lineTo(0,2);c.lineTo(-5,5);c.closePath();c.fill();c.restore();}
  function tick(now){const dt=Math.max(0,Math.min((now-last)/1000,.05));last=now;state.time+=dt;
    if(state.mode==='menu'){camera.position.set(3.1+Math.sin(state.time*.075)*.65,2.2,21);camera.lookAt(-.5,3.2,-35);W.environment(state.time,dt);menuZombies.forEach(e=>W.animateZombie(e,state.time,false,dt));}
    if(state.mode==='playing'){Tactical?.update(dt);state.runTime+=dt;state.sinceHit+=dt;state.shotCooldown=Math.max(state.shooting?-.02:0,state.shotCooldown-dt);state.recoil=Math.max(0,state.recoil-dt*.6);applyAimAssist(dt);syncTouchHUD();state.pitch=T.MathUtils.clamp(state.pitch,-1.15,1.15);camera.rotation.set(state.pitch,state.yaw,0,'YXZ');const targetFov=state.aim?(state.weapon===4?35:49):68;camera.fov=T.MathUtils.lerp(camera.fov,targetFov,Math.min(1,dt*12));camera.updateProjectionMatrix();movePlayer(dt);if(state.shooting)fire();if(state.reload>0){state.reload-=dt;if(state.reload<=0){state.reload=0;state.ammo=weapons[state.weapon].mag;sfx('reload');}hud();}W.gun.position.set(T.MathUtils.lerp(W.gun.position.x,state.aim?.025:(camera.aspect<1?.09:.28),dt*12),(camera.aspect<1?-.18:-.28)+(state.moving?Math.sin(state.runTime*11)*.008:0)-(state.reload>0&&state.reloadTotal>0?Math.sin(state.reload/state.reloadTotal*Math.PI)*.28:0),(camera.aspect<1?-.7:-.44)+state.recoil);W.gun.rotation.x=state.recoil*.8+(state.reload>0?-.35:0)+(Tactical?.healing?-.45:0);W.animateWeapon?.(state.recoil,state.reload,state.reloadTotal);const scoped=state.aim&&state.weapon===4&&!Tactical?.healing&&state.reload<=0;$('scope-overlay').classList.toggle('hidden',!scoped);document.body.classList.toggle('scoped',scoped);W.gun.visible=!scoped;state.blastShake=Math.max(0,(state.blastShake||0)-dt*.4);camera.rotation.z=Math.sin(state.runTime*70)*state.blastShake;if(state.time>(state.flashUntil||0)){W.muzzle.visible=false;W.muzzleLight.intensity=0;}if(state.spawnLeft>0&&zombies.length<22){state.spawnTimer-=dt;if(state.spawnTimer<=0){spawnEnemy();state.spawnTimer=Math.max(.6,1.4-state.wave*.07);}}
      updateEnemies(dt);
      if(state.mode==='playing'&&zombies.length===0&&state.spawnLeft===0){if(!state.waveCleared){state.waveCleared=true;state.nextWave=5;const bonus=state.wave*60;saved.money+=bonus;state.earned+=bonus;const healed=Math.ceil(Math.min(maxHp(),state.hp+25)-state.hp);state.hp=Math.min(maxHp(),state.hp+25);persist();banner('SECTOR CLEARED','₡ '+bonus+' クリア報酬'+(healed>0?' · 体力 +'+healed:'')+' · 次の襲撃まで5秒',4200);hud();}else{state.nextWave-=dt;if(state.nextWave<=0)beginWave();}}
      if(state.sinceHit>5&&saved.upgrades.regen>0&&state.hp<maxHp()){state.hp=Math.min(maxHp(),state.hp+saved.upgrades.regen*dt);hud();}W.environment(state.time,dt);updateEffects(dt);drawRadar();
    }
    if(state.mode==='playing'||state.mode==='menu')FX.update(state.time,dt,state.mode==='playing');
    renderer.render(scene,camera);
    if(!captureMode||++capturedFrames<2)requestAnimationFrame(tick);
    else renderer.domElement.toBlob(blob=>{if(!blob)return;const frame=document.createElement('img');const url=URL.createObjectURL(blob);frame.alt='実際のゲーム描画フレーム（診断モード）';frame.style.cssText='position:absolute;inset:0;width:100%;height:100%;object-fit:fill';frame.onload=()=>{renderer.domElement.style.visibility='hidden';document.body.dataset.capture='ready';URL.revokeObjectURL(url);};frame.src=url;$('game-world').appendChild(frame);},'image/png');
  }
  document.addEventListener('pointerlockchange',()=>{const locked=document.pointerLockElement===renderer.domElement;const was=state.pointerLocked;state.pointerLocked=locked;if(!locked&&was&&state.mode==='playing'&&$('overlay').classList.contains('hidden'))openModal('pause');});
  document.addEventListener('mousemove',e=>{if(state.mode!=='playing'||mobile)return;if(state.pointerLocked||state.dragLooking){const gain=.0022*touchPrefs.sensitivity*(state.aim?touchPrefs.adsSensitivity*(state.weapon===4?.8:1):1);state.yaw-=T.MathUtils.clamp(e.movementX,-250,250)*gain;state.pitch=T.MathUtils.clamp(state.pitch-T.MathUtils.clamp(e.movementY,-250,250)*gain,-1.15,1.15);}});
  renderer.domElement.addEventListener('mousedown',e=>{if(state.mode!=='playing'||mobile)return;if(e.button===0){if(!state.pointerLocked&&lockSupported&&!state.lockFailed){requestLock();return;}state.shooting=true;state.dragLooking=!state.pointerLocked;}if(e.button===2)state.aim=true;});
  document.addEventListener('mouseup',e=>{if(e.button===0){state.shooting=false;state.dragLooking=false;}if(e.button===2&&!mobile)state.aim=false;});
  renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());
  addEventListener('keydown',e=>{if(e.code==='Tab'&&!$('overlay').classList.contains('hidden')){const els=[...$('modal').querySelectorAll('button:not(:disabled),a[href],input:not(:disabled),[tabindex="0"]')];if(!els.length)return;const first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}return;}if(e.repeat)return;if(state.mode==='playing'&&(e.ctrlKey||e.metaKey||e.altKey))return;if(state.mode==='playing'){if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyA','KeyS','KeyD'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.code==='KeyR')reload();if(/^Digit[1-6]$/.test(e.code))switchWeapon(Number(e.code.slice(5))-1);if(e.code==='KeyQ')cycleWeapon(1);if(e.code==='KeyG')Tactical?.grenade();if(e.code==='KeyH')Tactical?.medkit();if(e.code==='KeyB')openModal('shop');if(e.code==='Escape'||e.code==='KeyP')openModal('pause');}else if(e.code==='Escape'&&!$('overlay').classList.contains('hidden')){backOrClose();}else if(e.code==='KeyB'&&state.mode==='paused'&&state.lastModal==='shop')closeOverlay();else if(e.code==='KeyP'&&state.mode==='paused'&&state.lastModal==='pause')closeOverlay();});
  addEventListener('keyup',e=>keys.delete(e.code));
  let wheelAt=0;addEventListener('wheel',e=>{if(state.mode!=='playing'||!$('overlay').classList.contains('hidden'))return;const now=performance.now();if(now-wheelAt<160||!e.deltaY)return;wheelAt=now;cycleWeapon(e.deltaY>0?1:-1);},{passive:true});
  addEventListener('blur',()=>{clearInput();if(state.mode==='playing')openModal('pause');});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();if(state.mode==='playing')openModal('pause');persist();}else{last=performance.now();if(state.mode!=='paused')setAudioActive(true);}});
  const pad=$('move-pad'),lookPad=$('look-pad'),firePad=$('mobile-fire');let joyPointer=null,lookPointer=null,firePointer=null,firePoint={x:0,y:0};
  function capture(el,e){try{el.setPointerCapture(e.pointerId);}catch(error){}}
  function touchLook(dx,dy){const gain=.0042*touchPrefs.sensitivity*(state.aim?touchPrefs.adsSensitivity*(state.weapon===4?.8:1):1);state.yaw-=T.MathUtils.clamp(dx,-80,80)*gain;state.pitch=T.MathUtils.clamp(state.pitch-T.MathUtils.clamp(dy,-80,80)*gain,-1.15,1.15);}
  function updateJoy(e){const rect=pad.getBoundingClientRect(),radius=rect.width*.32;let x=(e.clientX-rect.left-rect.width/2)/radius,y=(e.clientY-rect.top-rect.height/2)/radius;state.autoSprinting=touchPrefs.autoSprint&&y<-1.15&&Math.abs(x)<.75;const len=Math.hypot(x,y);if(len<.08){x=y=0;}else if(len>1){x/=len;y/=len;}joy.x=x;joy.y=y;$('move-knob').style.transform='translate('+x*38+'px,'+y*38+'px)';syncTouchHUD();}
  pad.addEventListener('pointerdown',e=>{if(state.mode!=='playing'||joyPointer!==null)return;e.preventDefault();joyPointer=e.pointerId;capture(pad,e);updateJoy(e);});pad.addEventListener('pointermove',e=>{if(e.pointerId===joyPointer&&state.mode==='playing')updateJoy(e);});
  function resetJoy(e){if(e.pointerId===joyPointer){joyPointer=null;joy.x=joy.y=0;state.autoSprinting=false;$('move-knob').style.transform='';syncTouchHUD();}}['pointerup','pointercancel','lostpointercapture'].forEach(type=>pad.addEventListener(type,resetJoy));
  lookPad.addEventListener('pointerdown',e=>{if(state.mode!=='playing'||lookPointer!==null)return;e.preventDefault();lookPointer=e.pointerId;look.x=e.clientX;look.y=e.clientY;capture(lookPad,e);});lookPad.addEventListener('pointermove',e=>{if(e.pointerId!==lookPointer||state.mode!=='playing')return;touchLook(e.clientX-look.x,e.clientY-look.y);look.x=e.clientX;look.y=e.clientY;});['pointerup','pointercancel','lostpointercapture'].forEach(type=>lookPad.addEventListener(type,e=>{if(e.pointerId===lookPointer)lookPointer=null;}));
  firePad.addEventListener('pointerdown',e=>{e.preventDefault();if(state.mode!=='playing'||firePointer!==null)return;firePointer=e.pointerId;firePoint={x:e.clientX,y:e.clientY};state.shooting=true;capture(firePad,e);fire();syncTouchHUD();});firePad.addEventListener('pointermove',e=>{if(e.pointerId!==firePointer||state.mode!=='playing')return;touchLook(e.clientX-firePoint.x,e.clientY-firePoint.y);firePoint={x:e.clientX,y:e.clientY};});['pointerup','pointercancel','lostpointercapture'].forEach(type=>firePad.addEventListener(type,e=>{if(e.pointerId===firePointer){firePointer=null;state.shooting=false;syncTouchHUD();}}));
  $('mobile-reload').addEventListener('click',()=>{reload();haptic(12);});$('mobile-aim').addEventListener('click',()=>{if(state.mode!=='playing')return;state.aim=!state.aim;haptic(10);syncTouchHUD();});$('mobile-sprint').addEventListener('click',()=>{if(state.mode!=='playing')return;state.touchSprint=!state.touchSprint;haptic(10);syncTouchHUD();});$('mobile-switch').addEventListener('click',()=>{if(state.mode!=='playing')return;const owned=[...saved.owned].sort((a,b)=>a-b);if(owned.length<2){toast('武器庫で別の武器を購入すると切り替えられます');return;}cycleWeapon(1);haptic(12);});
  touchReset=()=>{joyPointer=lookPointer=firePointer=null;state.dragLooking=false;};$('mobile-controls').addEventListener('contextmenu',e=>e.preventDefault());let lastLandscape=innerWidth>innerHeight;addEventListener('resize',()=>{const landscape=innerWidth>innerHeight;if(landscape!==lastLandscape&&state.mode==='playing')clearInput();lastLandscape=landscape;});
  Tactical=window.DZTactical({W,FX,state,getSaved:()=>saved,getEnemies:()=>zombies,maxHp,persist,hud,toast,kill,takeDamage,sfx,haptic});
  FX.onThunder=()=>sfx('thunder');
  hud();requestAnimationFrame(tick);setTimeout(()=>$('loading-screen').classList.add('done'),450);
  console.info('DEADZONE initialized: 5 enemy tiers, 6 weapons, 6 upgrades; WebGL renderer ready.');
  // Non-destructive integration checks, available explicitly at ?selftest=1.
  if(selfTesting){
    const backup=JSON.stringify(saved),snapshot={...state},originalPersist=storageAvailable;let passes=0,totalChecks=0;
    saved=emptySave();
    const check=(name,condition)=>{totalChecks++;console[condition?'info':'error']('TEST '+(condition?'PASS: ':'FAIL: ')+name);if(condition)passes++;};
    check('five enemy tiers with increasing health and unique rewards',tiers.length===5&&tiers.every((t,i)=>i===0||t.hp>tiers[i-1].hp&&t.reward>tiers[i-1].reward));
    check('six valid weapons',weapons.length===6&&weapons.every(w=>w.mag>0&&w.damage>0&&w.reload>0));
    check('empty wallet cannot buy rifle',(()=>{saved.money=0;return buyWeapon(3)===false;})());
    saved.money=5000;check('purchase deducts money and equips weapon',buyWeapon(3)&&saved.money===3500&&saved.owned.includes(3)&&state.weapon===3&&state.ammo===30);
    saved.upgrades.health=0;const before=saved.money;check('health upgrade charges correct price and heals',buyUpgrade('health')&&saved.money===before-180&&maxHp()===125&&state.hp===125);
    saved.upgrades.health=5;check('maximum upgrade cannot exceed limit',buyUpgrade('health')===false&&saved.upgrades.health===5);
    check('world boundaries block player',!canMove(30,0)&&!canMove(0,-100)&&canMove(0,17));
    const testEnemy=W.createZombie(0,0,-5);addHealthBar(testEnemy);zombies.push(testEnemy);const result=intersectEnemy(new T.Vector3(0,1.9,5),new T.Vector3(0,0,-1));check('ray detects headshots',result?.enemy===testEnemy&&result.head);
    const moneyBefore=saved.money;kill(testEnemy,true);check('kill grants tier reward and removes enemy',saved.money===moneyBefore+40&&zombies.length===0);
    clearEffects();saved=JSON.parse(backup);Object.assign(state,snapshot);storageAvailable=originalPersist;persist();W.buildGun(saved.equipped);hud();$('kill-feed').innerHTML='';$('toast').classList.remove('visible');
    ['shop','bestiary','guide','pause'].forEach(type=>{renderModal(type);check(type+' view renders',!!$('modal-content').textContent.trim());});$('modal-content').innerHTML='';
    console.info('Integration checks completed: '+passes+'/'+totalChecks+' passed. Save restored.');
    startGame();
    check('start transitions to gameplay and initial wave',state.mode==='playing'&&state.wave===1&&!$('game-hud').classList.contains('hidden'));
    state.ammo=5;reload();check('reload starts with correct duration',state.reload>0&&state.reloadTotal>0);state.reload=0;state.ammo=12;
    const shotAmmo=state.ammo;fire();check('shot consumes one round and activates muzzle flash',state.ammo===shotAmmo-1&&W.muzzle.visible);
    openModal('shop');check('shop pauses combat',state.mode==='paused'&&!$('overlay').classList.contains('hidden'));resumeGame();check('closing shop resumes combat',state.mode==='playing'&&$('overlay').classList.contains('hidden'));
    state.ammo=weapons[state.weapon].mag;state.shotCooldown=0;state.spawnLeft=6;
    const demo=W.createZombie(0,0,3);addHealthBar(demo);zombies.push(demo);hud();
    check('fivefold prop counts match all baseline categories',W.detailCounts.barrels===24*5&&W.detailCounts.sidewalkDebris===120*5&&W.detailCounts.roadScatter===70*5&&W.detailCounts.vegetation===160*5&&W.detailCounts.puddles===18*5);
    check('architectural geometry and new distinct props exist',W.detailCounts.windows>300&&W.detailCounts.airConditioners>30&&W.detailCounts.additionalProps===180);
    check('ULTRA uses native pixel density',renderer.getPixelRatio()===devicePixelRatio);
    const rigTest=W.createZombie(1,4,-10);check('articulated knees elbows wrists and ten fingers',rigTest.rig.knees.length===2&&rigTest.rig.elbows.length===2&&rigTest.rig.wrists.length===2&&rigTest.rig.fingers.flat().length===10);
    const gaitBefore=rigTest.anim.gait;rigTest.root.position.z+=.12;W.animateZombie(rigTest,1,true,.05);check('gait follows travelled distance and flexes knee independently',rigTest.anim.gait>gaitBefore&&rigTest.rig.knees[0].rotation.x!==rigTest.rig.hips[0].rotation.x);
    W.triggerAttack(rigTest);let contactCount=0;let early=W.animateZombie(rigTest,2,false,.1);check('attack has anticipation before damage contact',!early.impact&&rigTest.anim.attackTime>0);for(let i=0;i<100;i++)if(W.animateZombie(rigTest,2+i/60,false,1/60).impact)contactCount++;check('attack contact occurs exactly once then recovers',contactCount===1&&rigTest.anim.attackTime===-1);
    W.reactToHit(rigTest,true,-1);W.animateZombie(rigTest,4,false,.03);check('directional head hit reaction activates',rigTest.anim.hit>0&&rigTest.anim.hitHead&&rigTest.anim.hitSide===-1);
    for(let variant=0;variant<3;variant++){W.startDeath(rigTest,false);rigTest.anim.deathVariant=variant;for(let i=0;i<100;i++)W.animateDeath(rigTest,1/60);check('articulated death clip '+variant+' settles to ground',Number.isFinite(rigTest.rig.pelvis.position.y)&&rigTest.rig.pelvis.position.y<.4);}disposeEnemy(rigTest);
    $('mobile-aim').click();check('touch ADS button toggles aim and accessible state',state.aim&&$('mobile-aim').getAttribute('aria-pressed')==='true');$('mobile-aim').click();$('mobile-sprint').click();check('touch sprint toggle works',state.touchSprint===true);$('mobile-sprint').click();
    const yawBefore=state.yaw;firePad.dispatchEvent(new PointerEvent('pointerdown',{pointerId:91,clientX:300,clientY:500,bubbles:true}));firePad.dispatchEvent(new PointerEvent('pointermove',{pointerId:91,clientX:315,clientY:505,bubbles:true}));check('fire-and-drag changes view while firing',state.shooting&&state.yaw!==yawBefore);firePad.dispatchEvent(new PointerEvent('pointercancel',{pointerId:91,bubbles:true}));check('cancelled touch stops firing',!state.shooting&&firePointer===null);
    const prefBackup={...touchPrefs};openModal('settings');check('settings opens with seven live input controls',state.mode==='paused'&&$('modal-content').querySelectorAll('[data-pref]').length===7);$('pref-sensitivity').value='.75';$('pref-sensitivity').dispatchEvent(new Event('input',{bubbles:true}));check('touch settings slider applies immediately',touchPrefs.sensitivity===.75&&$('out-sensitivity').textContent==='75%');touchPrefs=prefBackup;applyTouchPrefs();resumeGame();state.yaw=state.pitch=0;state.ammo=weapons[state.weapon].mag;state.shotCooldown=0;hud();
    const tacticalSave=JSON.stringify(saved);Tactical.reset();state.mode='playing';saved.money=1000;saved.inventory={grenades:0,medkits:0};
    check('grenade purchase deducts price and increases stock',Tactical.buySupply('grenades')&&saved.money===880&&saved.inventory.grenades===1);
    saved.inventory.grenades=5;check('supply maximum blocks extra purchase',!Tactical.buySupply('grenades')&&saved.inventory.grenades===5);saved.money=0;check('insufficient funds blocks medical supply purchase',!Tactical.buySupply('medkits'));
    saved.inventory.grenades=2;state.mode='paused';check('paused game prevents grenade usage',!Tactical.grenade()&&saved.inventory.grenades===2);state.mode='playing';
    check('grenade consumes one unit and creates a projectile',Tactical.grenade()&&saved.inventory.grenades===1&&FX.projectiles.length===1);check('grenade cooldown prevents duplicate throw',!Tactical.grenade());
    for(let i=0;i<20;i++)FX.update(i*.1,.1,true);check('grenade detonates and is removed after fuse',FX.projectiles.length===0);
    state.hp=40;saved.inventory.medkits=1;state.reload=0;state.shotCooldown=0;state.ammo=8;check('medical treatment starts when injured',Tactical.medkit()&&Tactical.healing);fire();check('treatment prevents firing and preserves ammo',state.ammo===8);state.mode='paused';Tactical.update(3);check('paused time does not advance treatment',Tactical.healing&&state.hp===40);state.mode='playing';Tactical.update(2.1);check('treatment restores 60 health and consumes one kit',state.hp===100&&saved.inventory.medkits===0&&!Tactical.healing);
    state.hp=20;saved.inventory.medkits=1;Tactical.medkit();takeDamage(1);check('damage cancels treatment without consuming kit',!Tactical.healing&&saved.inventory.medkits===1);state.hp=maxHp();check('full health prevents wasteful kit use',!Tactical.medkit()&&saved.inventory.medkits===1);
    Tactical.beginWave(1);const contractMoney=saved.money;Tactical.onKill(true);Tactical.onKill(true);check('headshot contract completes and awards money',Tactical.mission.completed&&saved.money>=contractMoney+Tactical.mission.reward);const completedMoney=saved.money;Tactical.onKill(true);check('completed contract cannot award its reward twice',saved.money-completedMoney<=60&&Tactical.summary.contractsCompleted===1);check('rapid kills form a streak',Tactical.combo===3);Tactical.update(5.1);check('streak expires after five seconds',Tactical.combo===0);
    Tactical.beginWave(3);for(let i=0;i<3;i++){const enemy=W.createZombie(0,-3+i,-20);addHealthBar(enemy);zombies.push(enemy);}const blastKills=Tactical.blast(new T.Vector3(-2,.12,-20));check('grenade blast damages multiple enemies and advances blast contract',blastKills>=3&&Tactical.mission.completed);
    const shellsBefore=FX.shellCount;FX.shell(0);check('shot feedback creates a physical shell',FX.shellCount===shellsBefore+1);check('scenery ray finds facade impact',!!FX.surfaceHit(new T.Vector3(0,1.7,0),new T.Vector3(1,0,0)));check('weather can be switched off and on',FX.toggleWeather()===false&&FX.toggleWeather()===true);
    check('car body blocks the player across its full length (not a circle)',!canMove(-6.9+.3,5+2.0)&&canMove(-6.9+2.2,5-3.2));
    check('bullets stop at a car body but pass above a low barricade',!!W.rayObstacle(new T.Vector3(0,.8,5),new T.Vector3(-1,0,0),20)&&!W.rayObstacle(new T.Vector3(-5,1.6,0),new T.Vector3(0,0,-1),20));
    check('barrels are solid obstacles',W.obstacles.some(o=>o.shape==='cyl')&&!canMove(W.obstacles.find(o=>o.shape==='cyl').x,W.obstacles.find(o=>o.shape==='cyl').z));
    {const hb=W.createZombie(0,0,-5);addHealthBar(hb);check('health bar drains from its left anchor',hb.healthFill.center.x===0&&Math.abs(hb.healthFill.position.x+.35)<1e-6);zombies.push(hb);zombies.forEach(z=>z.root.updateMatrixWorld(true));const legShot=intersectEnemy(new T.Vector3(0,.5,5),new T.Vector3(0,0,-1));check('legs are hittable limb zones',legShot?.enemy===hb&&legShot.limb&&!legShot.head);zombies.splice(zombies.indexOf(hb),1);disposeEnemy(hb);}
    {const keep=state.ammo,keepW=state.weapon,keepOwned=[...saved.owned];saved.owned=[0,3];state.mode='playing';buyWeapon(0);state.ammo=4;buyWeapon(3);state.ammo=11;buyWeapon(0);check('field weapon switch keeps each magazine',state.ammo===4);buyWeapon(3);check('switching back restores the other magazine',state.ammo===11);saved.owned=keepOwned;buyWeapon(keepW);state.ammo=keep;}
    {state.hp=90;saved.inventory.medkits=1;Tactical.medkit();state.hp=maxHp();Tactical.update(2.1);check('kit is not consumed if HP filled during treatment',saved.inventory.medkits===1);}
    {const inv=saved.inventory.grenades;saved.inventory.grenades=0;Tactical.beginWave(3);check('blast contract falls back when no grenades',Tactical.mission.kind==='kills');saved.inventory.grenades=inv;}
    {const w0=FX.weather,w1=FX.toggleWeather(false),w2=FX.toggleWeather(false);check('weather toggle is reversible and reports its state',w1===!w0&&w2===w0&&FX.weather===w0);}
    state.shopTab='supplies';renderShop();check('supply shop renders two purchasable consumable types',$('modal-content').querySelectorAll('[data-supply]').length===2);state.shopTab='weapons';$('modal-content').innerHTML='';saved=JSON.parse(tacticalSave);startGame();const previewEnemy=W.createZombie(0,0,3);addHealthBar(previewEnemy);zombies.push(previewEnemy);$('toast').classList.remove('visible');$('damage-flash').style.opacity='0';hud();
    console.info('STORM integration checks completed: '+passes+'/'+totalChecks+' passed. Persistent storage writes disabled.');console.info('WORLD DETAIL COUNTS '+JSON.stringify(W.detailCounts));
    document.body.dataset.tests=passes===totalChecks?'passed':'failed';
    const diagnosticView=new URLSearchParams(location.search).get('view');if(['shop','settings','bestiary'].includes(diagnosticView))openModal(diagnosticView);if(diagnosticView==='supplies'){state.shopTab='supplies';openModal('shop');}
  }
})();
