'use strict';
/* Consumables, wave contracts and streak rewards. Persistence stays in the main save. */
window.DZTactical = function({W,FX,state,getSaved,getEnemies,maxHp,persist,hud,toast,kill,takeDamage,sfx,haptic}){
  const $=id=>document.getElementById(id),T=W.T;
  const supplies=[{id:'grenades',name:'M67 FRAG',jp:'破片手榴弾',price:120,max:5,icon:'◉',description:'1.8秒後に爆発。半径5.5m、中心で400ダメージ。壁や車両で跳ね返る。自爆に注意。'},{id:'medkits',name:'FIELD MEDKIT',jp:'応急回復キット',price:100,max:3,icon:'✚',description:'2秒間の治療で体力を60回復。移動は可能、射撃は不可。被弾で中断（キットは失わない）。'}];
  let mission=null,combo=0,comboRemaining=0,healRemaining=0,grenadeCooldown=0,contractsCompleted=0,earnedBonus=0;
  const inventory=()=>getSaved().inventory;
  function reward(amount){getSaved().money+=amount;state.earned+=amount;earnedBonus+=amount;persist();hud();}
  function beginWave(wave){const kind=['headshots','kills','grenadeKills'][(wave-1)%3],target=kind==='headshots'?Math.min(12,2+Math.floor(wave/4)):kind==='kills'?Math.min(6+Math.floor(wave/3),14):3;mission={kind,target,progress:0,reward:120+wave*40,completed:false};combo=0;comboRemaining=0;updateHUD();}
  function reset(){mission=null;combo=0;comboRemaining=0;healRemaining=0;grenadeCooldown=0;contractsCompleted=0;earnedBonus=0;FX.clear();updateHUD();}
  function onKill(head,source='gun'){combo=comboRemaining>0?combo+1:1;comboRemaining=5;const extra=combo>=2?Math.min(60,(combo-1)*10):0;if(extra)reward(extra);
    if(mission&&!mission.completed&&(mission.kind==='kills'||mission.kind==='headshots'&&head||mission.kind==='grenadeKills'&&source==='grenade')){mission.progress=Math.min(mission.target,mission.progress+1);if(mission.progress===mission.target){mission.completed=true;contractsCompleted++;reward(mission.reward);toast('作戦目標達成  ＋₡ '+mission.reward);sfx('buy');}}updateHUD();
  }
  function buySupply(id){const item=supplies.find(s=>s.id===id),saved=getSaved();if(!item||inventory()[id]>=item.max||saved.money<item.price)return false;saved.money-=item.price;inventory()[id]++;persist();hud();updateHUD();sfx('buy');toast(item.jp+' を補給しました');return true;}
  function grenade(){if(state.mode!=='playing'||grenadeCooldown>0||healRemaining>0)return false;if(inventory().grenades<=0){toast('手榴弾がありません。武器庫の「補給」で購入できます');return false;}inventory().grenades--;grenadeCooldown=1.2;W.camera.updateMatrixWorld();const direction=W.camera.getWorldDirection(new T.Vector3()),origin=W.camera.position.clone().addScaledVector(direction,.7);FX.throwGrenade(origin,direction,blast);persist();haptic(20);updateHUD();toast('手榴弾を投擲 — 爆発まで1.8秒');return true;}
  function blast(position){let count=0;for(const enemy of [...getEnemies()]){const distance=Math.hypot(enemy.root.position.x-position.x,.9*enemy.scale-position.y,enemy.root.position.z-position.z);if(distance>5.5)continue;enemy.hp-=400*(1-distance/7);W.reactToHit(enemy,false,enemy.root.position.x>position.x?1:-1);if(enemy.healthFill)enemy.healthFill.scale.x=.7*Math.max(0,enemy.hp/enemy.maxHp);if(enemy.hp<=0){count++;kill(enemy,false,'grenade');}}
    const playerDistance=W.camera.position.distanceTo(position);if(playerDistance<5.5)takeDamage(65*(1-playerDistance/5.5));sfx('explosion');haptic([30,30,60]);state.blastShake=.11*Math.max(0,1-playerDistance/20);hud();return count;
  }
  function medkit(){if(state.mode!=='playing'||healRemaining>0)return false;if(state.hp>=maxHp()){toast('体力は最大です');return false;}if(inventory().medkits<=0){toast('回復キットがありません。武器庫の「補給」で購入できます');return false;}healRemaining=2;state.shooting=false;state.aim=false;haptic(10);updateHUD();return true;}
  function cancelHeal(){if(healRemaining>0){healRemaining=0;toast('治療中断 — キットは消費されていません');updateHUD();}}
  function update(dt){if(state.mode!=='playing')return;grenadeCooldown=Math.max(0,grenadeCooldown-dt);comboRemaining=Math.max(0,comboRemaining-dt);if(comboRemaining===0)combo=0;if(healRemaining>0){healRemaining=Math.max(0,healRemaining-dt);if(healRemaining===0){inventory().medkits=Math.max(0,inventory().medkits-1);state.hp=Math.min(maxHp(),state.hp+60);persist();hud();haptic([10,35,20]);sfx('buy');toast('治療完了  体力 +60');}}updateHUD();}
  function updateHUD(){const inv=inventory();$('grenade-count').textContent=inv.grenades;$('medkit-count').textContent=inv.medkits;$('tactical-grenade').classList.toggle('empty',inv.grenades===0);$('tactical-medkit').classList.toggle('empty',inv.medkits===0);$('tactical-grenade').disabled=grenadeCooldown>0||healRemaining>0;$('tactical-medkit').classList.toggle('active',healRemaining>0);
    const progress=$('treatment-progress');progress.classList.toggle('hidden',healRemaining<=0);$('treatment-fill').style.width=(1-healRemaining/2)*100+'%';$('treatment-time').textContent=healRemaining.toFixed(1)+'s';
    $('streak-indicator').classList.toggle('hidden',combo<2||healRemaining>0);$('streak-value').textContent=combo;$('streak-time').style.width=comboRemaining/5*100+'%';
    if(mission){const names={headshots:'頭部を狙え',kills:'感染体を排除',grenadeKills:'爆破で一掃'};$('contract-label').textContent=mission.completed?'作戦目標達成':names[mission.kind];$('contract-progress').textContent=mission.progress+' / '+mission.target;$('contract-reward').textContent='₡ '+mission.reward;$('contract-fill').style.width=mission.progress/mission.target*100+'%';$('contract-panel').classList.toggle('complete',mission.completed);}
  }
  function supplyCards(){return supplies.map(item=>'<article class="item-card supply-card"><span class="item-tier">TACTICAL SUPPLY / CONSUMABLE</span><span class="supply-icon">'+item.icon+'</span><h3>'+item.name+'</h3><span class="item-jp">'+item.jp+'</span><p class="supply-description">'+item.description+'</p><div class="supply-stock">所持 <b>'+inventory()[item.id]+' / '+item.max+'</b></div><button data-supply="'+item.id+'" '+(inventory()[item.id]>=item.max||getSaved().money<item.price?'disabled':'')+'>'+(inventory()[item.id]>=item.max?'所持数上限':'₡ '+item.price+' — 1個補給')+'</button></article>').join('');}
  $('tactical-grenade').addEventListener('click',grenade);$('tactical-medkit').addEventListener('click',medkit);
  return {beginWave,reset,onKill,buySupply,grenade,medkit,cancelHeal,blast,update,updateHUD,supplyCards,get healing(){return healRemaining>0;},get mission(){return mission;},get combo(){return combo;},get summary(){return {contractsCompleted,earnedBonus};}};
};
